Task_1_1_2
KirShelestov/OOP pull request #5
Opened 2024-09-10 14:40 UTC by KirShelestov

2024-09-18 07:59 UTC, shadrina requested changes
Гуд

2024-09-18 07:59 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/Card.java
> +    CardInfo cardInfo;
См. инкапсуляция, модификаторы доступа.

2024-09-18 07:59 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/Card.java
> +                return ("Трефовая дама (" + this.getValue() + ")");
Скобки внешние ставить необязательно

2024-09-18 07:59 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/Card.java
> +        }
`return suit.toAdjective(cardInfo.gender()) + cardInfo;`

2024-09-18 07:59 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/Card.java
> +    public String toString() {
Почитай про аннотацию `@Override` и методы объекта `java.lang.Object`.

На лекциях еще не рассказывали, но будет очень полезно ознакомиться сначала самостоятельно.

2024-09-18 07:59 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/Deck.java
> +    public ArrayList<Card> getCards() {
В публичных сигнатурах мы стараемся не завязываться на конкретных реализациях используемых типов. Чем более общие типы в сигнатуре, тем для больших юзкейсов можно вызвать метод.

`ArrayList<T>` - это конкретная реализация для контейнера `List<T>`.

2024-09-18 07:59 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/Person.java
> +    Hand hand;
Аналогично см. инкапсуляция, модификаторы доступа.

2024-09-18 07:59 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/Person.java
> +        }
Я уверена, среда разработки это усиленно подсвечивает, намекая на упрощение.

2024-09-18 08:01 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/Card.java
> +    CardInfo cardInfo;
Есть еще полезный модификатор `final`, который тоже очень много где можно поставить.

2024-09-18 12:03 UTC, shadrina requested changes

2024-09-18 12:03 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/Deck.java
> +    public void addCards(ArrayList<Card> cards) {
Реализация контейнера в сигнатуре

2024-09-18 12:03 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/Hand.java
> +            while ((acesInNumber > 0) && (value > 21)) {
Для операторов предусмотрены приоритеты. Чтобы разработчик не ставил очень много скобок.
В данном случае все скобки лишние, кроме внешних скобок условий.

2024-09-18 12:03 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/Player.java
> +                if ((decision == 1) || (decision == 0)) {
Аналогично

2024-09-18 12:04 UTC, shadrina commented
У тебя достаточно много классов, они все лежат в общем пакете. Я думаю, их можно немного прибрать, сделав дополнительные подпакеты. Так будет легче и ревьюить, и в будущем смотреть/дополнять/менять свою объектную модель.

2024-09-18 12:05 UTC, shadrina commented
Я вижу, что у тебя еще много задач отправлено на ревью. Поправь в них, пожалуйста, все, что я написала здесь (если аналогичные ошибки имеются).

2024-09-18 12:18 UTC, KirShelestov commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/Deck.java
> +    public void addCards(ArrayList<Card> cards) {
Не совсем понял по поводу замечаний к данной реализации

2024-09-23 11:11 UTC, shadrina requested changes

2024-09-23 11:11 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/card/Card.java
> +public class Card {
Прекрасно, теперь это [record](https://docs.oracle.com/en/java/javase/17/language/records.html).

2024-09-23 11:11 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/card/CardInfo.java
> +    TEN("Десятка", 10, Gender.NEUTRAL),
В случае, когда какое-то значение в большинстве случаев превалирует, я делаю конструктор/метод/функцию со значением по умолчанию. В Java такой возможности нет, но есть перегрузка методов. В данном случае можно сделать конструктор с двумя параметрами, который будет по умолчанию выставлять Gender в NEUTRAL.

2024-09-23 11:11 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/card/CardInfo.java
> +    }
Они задуманы как package-private?

2024-09-23 11:11 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/card/CardInfo.java
> +    public Gender getGender() {
На будущее: если очень надоест писать геттеры/сеттеры/типовые конструкторы/оверрайды методов Object, существуют библиотеки, которые генерируют такой код автоматически, например, [Lombok](https://projectlombok.org/).

2024-09-23 11:11 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/card/Suit.java
> +    final String suitName;
Приучаем себя всегда думать о видимости.

2024-09-23 11:11 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/gamelogic/Deck.java
> +        return (!deck.isEmpty());
Скобки лишние

2024-09-23 11:11 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/gamelogic/Deck.java
> +        return cardToTake;
Что будет, если колода пустая?

2024-09-23 12:56 UTC, KirShelestov commented on Task_1_1_2/src/main/java/ru/nsu/shelestov/gamelogic/Deck.java
> +        return cardToTake;
В моей логике, такого не может произойти, т.к. я проверяю это в методе hit() в Person.java. Если колода пустая, то я уже использую другую колоду (стопку сброса).

2024-09-24 08:13 UTC, shadrina approved these changes

2024-09-24 08:32 UTC, merged